### ISSUE TITLE
Subgraph with rank = source or sink causes segfault

### ISSUE THREAD

**Issue by camwebb** [ellson/graphviz#1273] opened 2017-08-22 00:34 UTC
This graph:
```
digraph {
  a -> b
  { rank=source c}
}
```
causes a segfault with `dot`:
```
...
network simplex:  4 nodes 2 edges maxiter=2147483647 balance=2
Segmentation fault (core dumped)
```
Fails also with `rank=sink`, but successful with `max`,`min`,`same`. Checked on fresh build of nightly release: `graphviz-2.41.20170103.1755`. This seems to be the same issues as bug [223](http://www.graphviz.org/mantisbt/view.php?id=223), fixed in version 1.9.

[Thanks for `graphviz`!]

**Comment by emden** [comment] 2017-08-23 16:30
This is a duplicate of issue #1225 and has been fixed.

**Closed by emden** 2017-08-23 16:30 UTC

**Comment by camwebb** [comment] 2017-08-23 17:23
@emden Oops - sorry. I was working with an old (Jan) nightly, not the newest one - duh! Thanks.
